services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/laravel
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - php
    - vite
  php:
    build:
      context: .docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - .:/var/www/laravel
    environment:
      - VITE_HOST=vite
      - VITE_PORT=5173
      - VITE_DEV_SERVER_URL=http://vite:5173
    command: php-fpm
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - .docker/env/mysql.env
    volumes:
      - db_data:/var/lib/mysql
  composer:
    build:
      context: .docker/dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - .:/var/www/laravel
  artisan:
    build:
      context: .docker/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - .:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]
  vite:
    image: node:22-alpine
    working_dir: /var/www/laravel
    volumes:
      - .:/var/www/laravel
      - vite_node_modules:/var/www/laravel/node_modules
    ports:
      - "5174:5173"
    environment:
      - VITE_DEV_SERVER_URL=http://localhost:8080
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - php
    stdin_open: true
    tty: true

volumes:
  db_data:
  vite_node_modules:


    